# Generated by Django 4.1.3 on 2024-02-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caffeinecultureapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
