# Generated by Django 4.1.3 on 2024-02-21 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caffeinecultureapi', '0003_comment_parent_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caffeinecultureapi.comment'),
        ),
    ]
