# Generated by Django 4.1.3 on 2024-03-05 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caffeinecultureapi', '0007_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('content', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='caffeinecultureapi.comment')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messager', to='caffeinecultureapi.message')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='caffeinecultureapi.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caffeinecultureapi.user')),
            ],
        ),
    ]
